// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	NOTICE   string
	USER_MST string
	Country  string
}{
	NOTICE:   "NOTICE",
	USER_MST: "USER_MST",
	Country:  "country",
}
